### ISSUE TITLE
[Enhancement] 按钮效果需要改进

### ISSUE THREAD

**Issue by catfishlty** [luohc92/vue3-image-viewer#2]
![)QL31$(SC6O9C3U$6N K 8](https://user-images.githubusercontent.com/12734411/196038970-27dd8524-f3c5-4293-b378-c69296c3afff.png)

这几个按钮的阴影看起来怪怪的，个人认为可以给圆形按钮增加个同色窄边框。:)

**Comment by luohc92** [comment]
可以提供一下浏览器版本吗？这是兼容性导致的问题

**Comment by luohc92** [comment]
请更新最新版

**Comment by catfishlty** [comment]
感谢~
104版本会有这个问题，106版本就没问题了
