### ISSUE TITLE
关闭组件要关闭两次

### ISSUE THREAD

**Issue by gracefullliam** [luohc92/vue3-image-viewer#3]
<img width="1380" alt="image" src="https://github.com/luohc92/vue3-image-viewer/assets/103918944/44a52c8c-3c87-43b1-8090-e3b3e454e819">
<img width="1382" alt="image" src="https://github.com/luohc92/vue3-image-viewer/assets/103918944/18f3dc80-fe2b-436c-a912-8801432de160">

**Comment by luohc92** [comment]
春节期间在休息，不好意思。如果还有问题需要解决，请把调用代码提供一下，看效果应该是调用了两次，打开了两个图片查看器的窗口
